### ISSUE TITLE
Make Registration the home page for logged-in users

### ISSUE THREAD

**Issue by mpaluchowski** [Pragmatists/open-trapp-ui#18]
Now that we have long-lived tokens, it'd be much faster if the first page to open on initial load was Registration.

Right now we need to make two (!) additional clicks to get to Reporting: first the menu, then Reporting, and only then can we start logging time.

**Comment by HubertLegec** [comment]
It's implemented now. When not expired token is present and user navigates to OpenTrapp root URL it's redirected to registration page.
