### ISSUE TITLE
Menu disappears on smaller screens

### ISSUE THREAD

**Issue by mpaluchowski** [Pragmatists/open-trapp-ui#19]
It's nice to have the menu on the top bar now, but it disappears when the window (or screen) are made narrow.

![Screenshot from 2020-11-17 17-35-14](https://user-images.githubusercontent.com/727642/99418515-66b56b80-28fb-11eb-8c88-20f907154fd5.png)

**Comment by HubertLegec** [comment]
For which screen resolutions this scenario happens? 
For with > 1000px tabs should be visible on app bar.
For mobile version and width < 1000px there is a navigation bar present at the bottom of the page instead of tabs on top bar.

**Comment by mpaluchowski** [comment]
Hmm, I can't reproduce this now. Maybe because once I log in, there's no way to get to the start page anymore :) Anyway, closing.
