### ISSUE TITLE
Registration page refresh returns a 404

### ISSUE THREAD

**Issue by mpaluchowski** [Pragmatists/open-trapp-ui#4]
After I log in, the URL in the address bar is `https://pragmatists.github.io/open-trapp-ui/registration`. If I now hit F5 to refresh the page, I get a 404 Not Found. That's, I guess, because of GitHub pages not traversing to parent directories when it doesn't find a particular URL.

If I now change the URL to `https://pragmatists.github.io/open-trapp-ui/` and open the page, I land on the home page ("Welcome to OpenTrapp!"), I'm still logged in, and I have no way of going back to the registration page.

**Comment by HubertLegec** [comment]
Fixed
